# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d4a2e70354f0e03941c0060943bc564e"
name = "inklabs"
# ⚠️  This placeholder is automatically overridden by `shopify app dev` (automatically_update_urls_on_dev = true).
#   For production, replace with your actual deployed URL before running `shopify app deploy`.
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = true
